### ISSUE TITLE
ua status to provide unattended-upgrades status

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-pro-client#1244]
Transferred from: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1904756

'Unattended-upgrades' is something enabled by default, but most customers aren't aware of it nor have an easy way to visualize it.

While we are currently working to modify our current onboarding and all documentation to do a better job at communicating it, we think it might be interesting to have 'unattended-upgrades' status as part of the 'ua' client.

Example:

    $ ua status
    SERVICE AVAILABLE DESCRIPTION
    cc-eal no Common Criteria EAL2 Provisioning Packages
    esm-apps yes UA Apps: Extended Security Maintenance
    esm-infra yes UA Infra: Extended Security Maintenance
    fips no NIST-certified FIPS modules
    fips-updates no Uncertified security updates to FIPS modules
    livepatch yes Canonical Livepatch service
    => unattended-upgrades yes Automatic installation of security upgrade

**Comment by mitechie** [comment]
This is really interesting and fits ideas of "state of the machine" we have for future work. I don't know if it should show directly in status like this, or in a more "give me all the machine state" that's to be defined.

**Comment by slashdd** [comment]
I have report the bug for 'status' but 'disable' and 'enable' would be good to have as well (if feasible)

**Comment by lucasmoura** [comment]
We now have a specific Pro endpoint that provides information about `unattended-upgrades`:
https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/explanations/how_to_interpret_output_of_unattended_upgrades/?highlight=unattended

Even though this request is for the information to be presented on status, I believe the endpoint already tackle many needs regarding `unattended-upgrades`.. Because of that, I am closing this issue. However, please feel free to open it again if any of you believe it is still relevant for the Pro tool.
