### ISSUE TITLE
tech-debt: make cache keys static vars to avoid typos at delete_cache_key and read_cache callsites

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1340]
https://github.com/canonical/ubuntu-advantage-client/blob/e8506a61028e9485a09fbc113b5f70d068787738/uaclient/config.py#L60-L68

**Comment by orndorffgrant** [comment]
Tracking in SC-926

**Comment by lucasmoura** [comment]
Since we have started to refactor the config module, I believe we should no longer have any `data_paths` definitions here.
Every file should have an associated `UAFile` and they should not be handled by the config module. This will address this issue while also making the `config`  module less bloated, as we aim for it to only handle the user Pro config file

**Comment by orndorffgrant** [comment]
The refactor @lucasmoura mentioned is completed so this issue is OBE.
