### ISSUE TITLE
Product and API specific constants should be configurable

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1405]
Make entitlements and any API URLs configurable or overridable

    help_doc_url = "https://ubuntu.com/cc-eal"                                  
    name = "cc-eal"                                                             
    title = "CC EAL2"                                                           
    description = "Common Criteria EAL2 Provisioning Packages"                  
    repo_key_file = "ubuntu-cc-keyring.gpg"                                     
    is_beta = True

**Comment by orndorffgrant** [comment]
Tracking in SC-893

**Comment by orndorffgrant** [comment]
I'm not sure we want these to be configurable anymore. Some of these are translated or need to have a specific value otherwise something will break (name, repo_key_file)

For is_beta and possibly help_url, I think the preference would be to have those move to the backend resource definitions.

So in total I think we can close this? WDYT @renanrodrigo @lucasmoura @blackboxsw ?

**Comment by renanrodrigo** [comment]
I'd say close this one and open a new one with the problem we want to solve: move all things we don't really need in the client to the Contracts Server somehow :D

**Comment by orndorffgrant** [comment]
Added #2825 and #2826
