### ISSUE TITLE
fix: better handle apt errors

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-pro-client#1452]
Currently, if we have an apt error during `ua fix`, we will raise the exception caused to the user as is. We can improve that output by directly saying that an apt error has caused the ua fix command to fail

**Comment by orndorffgrant** [comment]
Tracking in SC-823

**Comment by renanrodrigo** [comment]
When this issue was raised, `fix` had a different code flow. Now that it relies on plan+execute, it seems to be using the `apt ` module functionality and error messages are clearer - would be nice to have an example of how they were before...

Anyways, I broke `apt-get` on purpose and got this messages when running fix
```
APT update failed.
Unexpected APT error.
Invalid command specified 'apt-get update'.
See /var/log/ubuntu-advantage.log
```
I think this is pretty much good, as we are telling that APT failed, and then presenting the exact exception message, and finally pointing to the logs. I don't think this issue is valid anymore, we can close it. WDYT @lucasmoura @orndorffgrant

**Comment by orndorffgrant** [comment]
@renanrodrigo did it go on to say "CVE-1234 is not resolved"? I think that was the desired outcome of this bug

**Comment by renanrodrigo** [comment]
Of course, sorry
let me paste the full output here
```
root@focal-sut:~# pro fix USN-4539-1
USN-4539-1: AWL vulnerability
Associated CVEs:
 - https://ubuntu.com/security/CVE-2020-11728

Fixing requested USN-4539-1
1 affected source package is installed: awl
(1/1) awl:
A fix is available in Ubuntu standard updates.
{ apt update && apt install --only-upgrade -y libawl-php }
APT update failed.
Unexpected APT error.
Invalid command specified 'apt-get update'.
See /var/log/ubuntu-advantage.log

1 package is still affected: awl
✘ USN-4539-1 is not resolved.
```

This tells explicitly that an APT error ocurred, when it happened, and that the USN is not resolved.

**Comment by orndorffgrant** [comment]
Yep that looks good to me then - @lucasmoura can confirm this is what he was hoping for on monday.
