### ISSUE TITLE
fix: error processing USN.release_packages no source_link = None.

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1465]
Awaiting decision from security (@stevebeattie) to determine whether UA Client needs to [change logic per Security team's preferred direction](https://github.com/canonical/ubuntu-advantage-client/issues/1465#issuecomment-805067057)
---------------------

To reproduce on xenial: ua fix USN-4770-1
UA client finds related USN-3752-3 which provides empty USN.release_packages binary package "source_links" for any gcp/gke kernel binaries.

Example sparse USN.release_packages from USN-3752-3. Is this behavior expected for kernel-related USNs?
```bash
     {
      "is_source": false,
      "name": "linux-image-4.15.0-1027-gcp",
      "source_link": "https://launchpad.net/ubuntu/+source/linux-gcp",
      "version": "4.15.0-1027.28",
      "version_link": "https://launchpad.net/ubuntu/+source/linux-gcp/4.15.0-1027.28"
     },
     {
      "is_source": false,
      "name": "linux-image-4.15.0-1033-oem",
      "source_link": "https://launchpad.net/ubuntu/+source/linux-oem",
      "version": "4.15.0-1033.38",
      "version_link": "https://launchpad.net/ubuntu/+source/linux-oem/4.15.0-1033.38"
     },
     {
      "is_source": false,
      "name": "linux-image-gke",
      "source_link": null,
      "version": "4.15.0.1027.29",
      "version_link": null
     },
     {
      "is_source": false,
      "name": "linux-image-gcp",
      "source_link": null,
      "version": "4.15.0.1027.29",
      "version_link": null
     },
     {
      "is_source": false,
      "name": "linux-image-oem",
      "source_link": null,
      "version": "4.15.0.1033.38",
      "version_link": null
     },
     {
      "is_source": false,
      "name": "linux-image-4.15.0-1029-kvm",
      "source_link": "https://launchpad.net/ubuntu/+source/linux-kvm",
      "version": "4.15.0-1029.29",
      "version_link": "https://launchpad.net/ubuntu/+source/linux-kvm/4.15.0-1029.29"
     },
```
This results in the following traceback
```bash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 999, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1055, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 266, in action_fix
    security.fix_security_issue_id(cfg, args.security_issue)
  File "/usr/lib/python3/dist-packages/uaclient/security.py", line 496, in fix_security_issue_id
    usn_released_pkgs = merge_usn_released_binary_package_versions(usns)
  File "/usr/lib/python3/dist-packages/uaclient/security.py", line 438, in merge_usn_released_binary_package_versions
    for src_pkg, binary_pkg_versions in usn.release_packages.items():
  File "/usr/lib/python3/dist-packages/uaclient/security.py", line 381, in release_packages
    source_pkg_name = pkg["source_link"].split("/")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by blackboxsw** [comment]
In MM discussion, some kernel metapackages will never have a source_link as those metapkgs is_source= true  will not be represented in the USN.release_packages.  Either of the following seems a viable solution:
- [ ] Security to publish source package information for all related binaries in (might involve more work on CVETracker to filter out that metadata)
- [ ] UA Client to change logic (currently keyed by src package name) to allow looking directly for binary package names which are unrelated to a defined src package.

**Comment by stevebeattie** [comment]
Hi,

For this specific issue, this is because of how kernel packages are delivered in Ubuntu, they end up being provided by two or three different source pacakges for each kernel, and we are only including information about one of those packages to the web team api. I think I can fix that, and additionally I think with some effort we can backfill that information to existing USNs, but I don't have a timeline for when our team can address it.

We DO want the binary packages that are listed to be taken into account, even without the source listing, becuase they are the meta packages that end up driving and pulling in the new kernel binary packages for a security update.

A related issue is that for packages in the ESM archive will contain source links that are (a) currently invalid (point to the wrong place) and (b) even if they did point to the right place, they would not be publicly visible to anyone outside of the teams that have the ability publish pacakges to the ESM repositiories. You can see an example of this in [the json for USN 4875-1](https://ubuntu.com/security/notices/USN-4875-1.json?show_hidden=true), where for example the xenial/opensmtpd binary entry includes a source link to https://launchpad.net/ubuntu/+source/opensmtpd/5.7.3p2-1ubuntu0.1~esm2 which does not exist, and has a different (private) URL within launchpad. Is that an issue for the UA client?

**Comment by lucasmoura** [comment]
Hi @stevebeattie I don't think this will be a problem for us. In `uaclient` we use the `source_link`  to extract the name of the `binary_package`. Looking at the example you have provided, I don't think this will be an issue for us, since the binary package name if in the end of the url as we expect.

But I will let @blackboxsw confirm that

**Comment by stevebeattie** [comment]
@lucasmoura thanks for the info. I think we can provide that for recent USNs where they are missing, and are planning to start work on it shortly. (There will possibly be significantly older (as in, several years old) USNs where we will not be able to provide the information.)

**Comment by stevebeattie** [comment]
A status update on this issue: the security team very recently landed a fix to our process to ensure that going forward there will be source links and source version links [1] included in all the USN info submitted to the website api and thus be available there. As an example of where this is the case, compare [USN-5003-1](https://ubuntu.com/security/notices/USN-5003-1) ([json](https://ubuntu.com/security/notices/USN-5003-1.json)) versus [USN-4979-1](https://ubuntu.com/security/notices/USN-4979-1) ([json](https://ubuntu.com/security/notices/USN-4979-1.json)).

There is still work to be done on the security team's side to backfill this information for existing USNs.

[1] With again the caveat that for esm-infra and esm-apps updates these links will be incorrect, and there *may* bey some rare situations where the version info may be inaccurate.

**Comment by lucasmoura** [comment]
This problem has not affected the Pro client in a long time now, so I believe the applied fix was sufficient here. I am closing this issue now, but if any of us detect that same problem in the future, we should reopen it.
