### ISSUE TITLE
Usability: request for `ua status --beta` to filter list of services that are beta

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#2061]
It is a bit confusing for customers trying to enable a beta service via `ua enable --beta`  and have no designation from `ua status` or `ua status --all` active services that are "beta". Would it make sense to surface a `ua status --beta` param that'd limit the services in the response to just beta services?

**Comment by lucasmoura** [comment]
Thanks for raising that @blackboxsw, after discussing it with the team we believe that we could either:

1) Have that on status, but using a different flag, so just because we have been using the `--beta` flag for actual beta functionality on other services
2) Display that a service is beta directly on the output of `ua status`.

But we can better discuss this for sure

**Comment by renanrodrigo** [comment]
This is now obsoleted by #2847 
The whole beta experience needs a redesign, and that should happen when we happen to have beta services again
