### ISSUE TITLE
ua/pro/ubuntu-advantage does not disable the MOTD advertising ESM updates

### ISSUE THREAD

**Issue by iconoclasthero** [canonical/ubuntu-pro-client#2458]
Why can't this just be a simple process via ua or pro?  There's no need to advertise these services and going the long way round to disable things via e.g., https://askubuntu.com/questions/1453749/inhibit-esm-messages-at-login isn't efficient and will probably cause issues down the line.

**Comment by iconoclasthero** [comment]
Amazing, now this has metastasized to apt:
```
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libimage-magick-perl imagemagick libopusfile0 libopenexr25
  libmagickcore-6.q16-6-extra libimage-magick-q16-perl libmagickwand-6.q16-6
  imagemagick-6.q16 libmagickcore-6.q16-6 imagemagick-6-common
Learn more about Ubuntu Pro at https://ubuntu.com/pro
``` 

Stop, just stop with this, it's cluttering everything up.  I don't understand why I cannot access these now if there are actual security updates despite apt stating that the very first one is up to date.  Beyond that, is ESM implying that it is holding security updates back from apt?

What the serious fuc,k is going on that these advertisements need to clutter up my MotD & APT and HOW THE FUCK DO I TURN THEM OFF EASILY!?

**Comment by iconoclasthero** [comment]
```
$ apt purge ubuntu-advantage-tools 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apturl-common distro-info gir1.2-goa-1.0 gir1.2-snapd-1 python3-debconf python3-distupgrade python3-update-manager ubuntu-release-upgrader-core
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  apturl* nautilus-share* software-properties-gtk* ubuntu-advantage-desktop-daemon* ubuntu-advantage-tools* ubuntu-desktop* ubuntu-desktop-minimal* ubuntu-minimal* ubuntu-release-upgrader-gtk* update-manager*
  update-manager-core* update-notifier* update-notifier-common*
0 upgraded, 0 newly installed, 13 to remove and 2 not upgraded.
After this operation, 5,152 kB disk space will be freed.
Do you want to continue? [Y/n] n
```
There's a lot of shit there that I'm not sure is acceptable to remove.  `software-properties-gtk` & `ubuntu-desktop` & `update-manager` sound pretty important so I'm a bit hesitant to do that.  What do the *s mean on the packages that will be "REMOVED" mean?

Can this be done safely by  just "masking the service units from systemd, like this:
```
$ sudo systemctl mask apt-news.service
$ sudo systemctl mask esm-cache.service
``` 
" (https://askubuntu.com/questions/1452519/what-are-the-services-apt-news-and-esm-cache-and-how-do-i-disable-them)

It seems like these messages upset users but Canonical/ESM/Pro/whatever feels they're under no obligation to explain what these messages mean or how to disable them.  Why not create a link on https://ubuntu.com/pro to show how to disable these messages?  Obviously I am not the only one to complain about this since my very first hit was an askubuntu link on how to disable this exact thing.

**Comment by iconoclasthero** [comment]
What the serious fuck?  Here it suggests that simply uninstalling the ubuntu-advantage-tools package does fuck up one's system:  https://askubuntu.com/questions/1371014/what-is-ubuntu-advantage-doing-on-my-fully-supported-20-04-box-what-is-it-che

**Comment by iconoclasthero** [comment]
Not that this is obvious, but why isn't this sufficient to stop the services and the messages?  Why isn't there some easy and safe way to get rid of this fucking utility?

```
$ sudo ua status; sudo ua disable esm-infra; sudo ua disable esm-apps ; sudo ua status
SERVICE          AVAILABLE  DESCRIPTION
esm-apps         yes        Expanded Security Maintenance for Applications
esm-infra        yes        Expanded Security Maintenance for Infrastructure
livepatch        yes        Canonical Livepatch service
realtime-kernel  yes        Ubuntu kernel with PREEMPT_RT patches integrated

This machine is not attached to an Ubuntu Pro subscription.
See https://ubuntu.com/pro
To use 'esm-infra' you need an Ubuntu Pro subscription
Personal and community subscriptions are available at no charge
See https://ubuntu.com/pro
To use 'esm-apps' you need an Ubuntu Pro subscription
Personal and community subscriptions are available at no charge
See https://ubuntu.com/pro
SERVICE          AVAILABLE  DESCRIPTION
esm-apps         yes        Expanded Security Maintenance for Applications
esm-infra        yes        Expanded Security Maintenance for Infrastructure
livepatch        yes        Canonical Livepatch service
realtime-kernel  yes        Ubuntu kernel with PREEMPT_RT patches integrated

This machine is not attached to an Ubuntu Pro subscription.
See https://ubuntu.com/pro

```

[jammy](https://manpages.ubuntu.com/manpages/jammy/) ([1](https://manpages.ubuntu.com/manpages/jammy/man1)) [ua.1.gz](https://manpages.ubuntu.com/manpages.gz/jammy/man1/ua.1.gz)

Provided by: [ubuntu-advantage-tools_27.7~22.04.1_amd64](https://launchpad.net/ubuntu/jammy/+package/ubuntu-advantage-tools) bug

NAME
       ubuntu-advantage - Manage Ubuntu Advantage services from Canonical

SYNOPSIS
       ua <command> [<args>]
       ubuntu-advantage <command> [<args>]

DESCRIPTION
       Ubuntu  Advantage  is  a  collection of services offered by Canonical to Ubuntu users. The
       Ubuntu Advantage command line tool is used to attach  a  system  to  an  Ubuntu  Advantage
       contract  to  then  enable and disable services from Canonical. The available commands and
       services are described in more detail below.

COMMANDS
       attach [--no-auto-enable] [--attach-config=/path/to/file.yaml] <token>
              Connect an Ubuntu Advantage support contract to this machine.

              The token parameter can be obtained from https://auth.contracts.canonical.com/.

              The --attach-config option can be used  to  provide  a  file  with  the  token  and
              optionally,  a  list  of  services  to  enable after attaching. The token parameter
              should not be used if this option is provided. An attach config file looks like the
              following:
                  token: YOUR_TOKEN_HERE  # required
                  enable_services:        # optional list of service names to auto-enable
                      - esm-infra
                      - esm-apps
                      - cis

              The  optional  --no-auto-enable  flag  will  disable  the  automatic  enablement of
              recommended entitlements which  usually  happens  immediately  after  a  successful
              attach.

              The exit code can be:
                  0: on successful attach
                  1: in case of any error while trying to attach
                  2: if the machine is already attached

       collect-logs [-o <file>| --output <file>]
              Create a tarball with all relevant UA logs and debug data.

              The  --output  parameter defines the path to the tarball. If not provided, the file
              is saved as ua_logs.tar.gz in the current directory.

       detach Remove the Ubuntu Advantage support contract from this machine. This also  disables
              all enabled services that can be.

       disable [cc-eal|cis|esm|fips|fips-updates|livepatch|ros|ros-updates]
              Disable this machine's access to an Ubuntu Advantage service.

**Comment by cpaelzer** [comment]
Hi @iconoclasthero ,
sorry that you feel that bad about it, but let me break down the different aspects of your report and try to answer (or redirect to the place this aspect already came up) accordingly.

> So is Canonical saying that ESM is holding security updates back from apt/main repos?

There has been an extensive discussions in forums, chat, bugs and a sync with various community leads ending up in an [FAQ document](https://discourse.ubuntu.com/t/ubuntu-pro-faq/34042) that answers this and more similar questions. It will soon - once it settled a bit and we are sure that no further questions are actually frequently asked - also move to the [official documentation](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/).

No, there is no holding back of anything - here the TL;DR for you in regard to your question: "If you decide to opt-in to Ubuntu Pro with either a free personal subscription or an enterprise subscription, you will get more security updates than ever before. If you don’t opt-in then there is no loss, you can continue using Ubuntu LTS without the Pro subscription as you always did."
It is explained more in detail there and so far most "Arr I hate this reactions" are from misunderstanding what pro is and what it provides - so consider having a read of the full FAQ if you can afford the time.

> There's no need to advertise these services

This not much advertising, much more it is helping people to realize that they could benefit from additional free support.
Without any hints less people would know and benefit and thereby Ubuntu would fail to provide as much as possible to every user out there.

> Amazing, now this has metastasized to apt

While there is a very small fraction of people that are like "oh no - I do not want to see those" there is a much bigger set of people that are like "interesting, I want to know more especially since it is free for me". BTW the [documentation describes all the different apt related messages](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/explanations/apt_messages.html?highlight=apt%20news) that you could see in different situations.

To be clear, in the discussions that already happened about disabling the apt messages there were several voices quite the opposite of you, even preferring to make it hard(er) to hide them - The messages make you aware of unused security support and in that regard is like the pings your car gives you if you do not wear your safety belt.
But the same discussion identified that some people just do not want to see them no matter what -  and so now nowadays there are ways to do that.
In regard to the apt_news you can use `sudo pro config set apt_news=false` to disable them.
Furthermore the documentation clearly points you to the files that make [apt](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/explanations/apt_messages.html?highlight=apt%20news#how-are-apt-configured-to-deliver-those-messages) and [motd](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/explanations/motd_messages.html?highlight=motd) messages happen - there you can disable even the hooks behind them if they bother you.
This is even outlined more clearly and straight forward in [the FAQ I mentioned](https://discourse.ubuntu.com/t/ubuntu-pro-faq/34042), see "Can I disable Ubuntu Pro notifications?"

Sometime you might find an old post/discussion/doc which isn't yet as clear on how to disable/remove the messaging. To explain that be aware, as I mentioned above, that initially the stance was more "people should know that they could have more coverage and not be allowed to be unaware to later regret it" but the discussions I mentioned have ended up in documenting how to disable all of it as shown above.

> Why not create a link on https://ubuntu.com/pro to show how to disable these messages?

On this I can only agree, we are already adding more links to the docs (and the FAQ) to many places. I'm not entirely sure if one from the more product sided https://ubuntu.com/pro is already on that task list. We will do so.

> What do the *s mean on the packages that will be "REMOVED" mean?
> 
> This [link from askubuntu.com](https://askubuntu.com/questions/1371014/what-is-ubuntu-advantage-doing-on-my-fully-supported-20-04-box-what-is-it-che) suggests that simply uninstalling the ubuntu-advantage-tools package could break one's system.

This is an entirely different aspect, which is more about "could this package be removable". This was discussed even longer ago in bug 1950692 and ended mostly by @vorlonofportland summary in [this comment](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1950692). Since then there have been complaints, but no new technical reasons to reconsider the decision. Steve clearly left the option open to revisit once there are reasons other than "taste". So please feel free to chime in there if you want.

> Not that this is obvious, but why isn't ua disable esm-apps esm-infra sufficient to stop the services and the messages?

esm-apps and esm-infra are services that you could enable with a subscription.
If you would use them and have them enabled, then it would look like:

```
$ pro status
SERVICE          ENTITLED  STATUS    DESCRIPTION
esm-apps         yes       enabled   Expanded Security Maintenance for Applications
esm-infra        yes       enabled   Expanded Security Maintenance for Infrastructure
```

And then `pro disable esm-apps` would disable that particular service, just as the help text and docs would tell you:

```
$ pro disable --help
usage: pro disable <service> [<service>] [flags]

Disable an Ubuntu Pro service.

Arguments:
  service              the name(s) of the Ubuntu Pro services to disable. One of: cc-eal, esm-apps, esm-infra, fips, fips-updates, livepatch, realtime-kernel, ros, ros-updates, usg
```

But without it being enabled in the first place your suggestion of `ua disable esm-apps esm-infra` will not be able to do anything as they are not enabled.

For now I see three things here I'd take away we could really work on (the rest is mostly discussions which already happened in other places as referred above):
1. @renanrodrigo since you are reworking the `pro status` output, I think in the case above the status of "AVAILABLE=>Yes" was misunderstood as there would be something that is already active and needs to be disabled from the users POV. Please take this into consideration that it might be worthwhile to make it even more clear that at this point it isn't yet enabled. An unattached system could still show the status column and list them all as disabled? Not sure how compatible that is with all the other requests we have, but adding the thought there would be good to avoid the case of @iconoclasthero trying to disable the service while it isn't enabled in the first place. @renanrodrigo If you agree carry this to the spec discussions about that please and ping back here if you have done so (or why not).
2. @orndorffgrant (distributing these things round robin) I was recreating the case of @iconoclasthero and while disabling a service that is not enabled isn't a very important case currently it just gives the "_To use 'esm-apps, esm-infra' you need ..._" text. Maybe - in this condition - there could be an additional "Asked to disable, but <service> isn't enabled"? @orndorffgrant If you agree file an separate issue please to work on that later and ping back here with the reference to it.
3. @s-makin I know you have a whole list of places where I wanted links to the documentation to be added. The reporter asks for one from https://ubuntu.com/pro and I agree that it should have a link to the pro(-client) documentation. If not already on your add-links list could you please add it there?

**Comment by renanrodrigo** [comment]
About (1)
Standardizing the tables in status is already part of the ongoing work, and it is covered there.

**Comment by s-makin** [comment]
About (3) - I think that makes sense. I'll need to liaise with the web team to get that added, but I'll report back here when it's done.

**Comment by orndorffgrant** [comment]
I created #2487 for (2)

**Comment by iconoclasthero** [comment]
Well, it is back.  I have no idea what more I could possibly do to get rid of that notification from my MOTD short of removing the ability of 90-updates-available to run.  
I looked at the FAQ.  It said to edit /etc/apt/apt.conf.d/20apt-esm-hook.conf.  I've removed  /etc/apt/apt.conf.d/20apt-esm-hook.conf:
```
.rw-r--r--  243 root 16 Dec  2009 20dbus
.rw-r--r-- 2.2k root  9 Feb  2019 50apt-file.conf
.rw-r--r--  129 root 26 Nov  2020 10periodic
.rw-r--r--  108 root 26 Nov  2020 15update-stamp
.rw-r--r--   85 root 26 Nov  2020 20archive
.rw-r--r--  305 root 26 Nov  2020 99update-notifier
.rw-r--r--   80 root 19 Feb  2021 20auto-upgrades
.rw-r--r--  625 root  8 Dec  2021 50command-not-found
.rw-r--r-- 6.2k root 14 Jan  2022 50unattended-upgrades
.rw-r--r-- 1.0k root 17 Feb  2022 20packagekit
.rw-r--r--  182 root 20 Feb  2022 70debconf
.rw-r--r-- 2.6k root 22 Feb  2022 50appstream
.rw-r--r--  435 root 22 Feb  2022 60icons
.rw-r--r--  251 root 22 Feb  2022 60icons-hidpi
.rw-r--r--   92 root  8 Apr  2022 01-vendor-ubuntu
.rw-r--r--  630 root  8 Apr  2022 01autoremove
.rw-rw-r--   40 root 23 Sep  2022 00trustcdrom
.rw-rw-r--   49 root 23 Sep  2022 00aptitude
lrwxrwxrwx   35 root 24 Sep  2022 88libdvdcss-pkg -> /usr/lib/libdvd-pkg/88libdvdcss-pkg
.rw-r--r--  127 root  1 Dec  2022 20snapd.conf
```
The message is coming from:
```
$ cat /etc/update-motd.d/90-updates-available

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

12 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm
```

That's coming from  /var/lib/update-notifier/updates-available.  ...  you know what?  this is so frustrating I just want a straight answer:

**How do i disable these messages?**

**Comment by iconoclasthero** [comment]
I went onto #ubuntu and asked how to disable these messages.  You know the response?  Install Debian.  That's fantastic!  There've been a lot of complaints about this and there is still no simple utility to stop the messages.  Why can't you all get it together and make something that will just stop them?!?!?!

**Comment by iconoclasthero** [comment]
@orndorffgrant: Thank you, I figured all that out on Friday but had decided to stop posting angry and frustrated messages by then.

I found apt-check and its write_human_readable_summary function and commented out 
```
231 #    if have_esm_infra is not None and esm_distro:
232 #        _output_esm_service_status(
233 #            outstream, have_esm_infra, service_type="Infrastructure"
234 #        )
235 #
236 #    if have_esm_apps is not None and lts_distro and not esm_distro:
237 #        _output_esm_service_status(
238 #            outstream, have_esm_apps, service_type="Applications"
239 #        )

⋮

270 #    if all(
271 #        [
272 #            have_esm_apps is not None,
273 #            not have_esm_apps,
274 #            lts_distro,3
275 #            not esm_distro
276 #        ]
277 #       ):
278 #        _output_esm_package_alert(
279 #            outstream, service_type="Apps",
280 #            disabled_pkg_count=disabled_esm_apps_updates)
281 #
282 #    if have_esm_infra is not None and not have_esm_infra and esm_distro:
283 #        _output_esm_package_alert(
284 #            outstream, service_type="Infra",
285 #            disabled_pkg_count=disabled_esm_infra_updates,
286 #            is_esm=True
287 #        )
```

Presumably by just setting that "return False" value still allows those functions to be called without them writing to ` /var/lib/update-notifier/updates-available `.  I fully anticipate that when update-notifier-common 3.192.54.6 is updated, that too will be overwritten so I saved a reference copy to apt_check.py.patched.  

Inre the apt hook in /etc/apt/apt.conf.d:
I moved 20apt-esm-hook.conf back to /etc/apt/apt.conf.d , commented 
```
//APT::Update::Post-Invoke-Stats {
//	"[ ! -f /usr/lib/ubuntu-advantage/apt-esm-hook ] || /usr/lib/ubuntu-advantage/apt-esm-hook || true";
//};

//binary::apt::AptCli::Hooks::Upgrade {
//	"[ ! -f /usr/lib/ubuntu-advantage/apt-esm-json-hook ] || /usr/lib/ubuntu-advantage/apt-esm-json-hook || true";
//};
```
and saved a patched copy as /etc/apt/apt.conf.d/~20apt-esm-hook.conf.patched~ with a comment back to this thread.

**Comment by iconoclasthero** [comment]
On Friday, I coincidentally (and unrelatedly) happened across [this post:](https://www.digitaltrends.com/computing/uninstalled-windows-on-my-gaming-pc-dont-want-to-go-back/) .  The relevant section of it for this discussion is:

> There are a few reasons [to switch to linux], even if the scales generally fall in favor of Windows. For one, Linux is free from any central authority. You don’t have to worry about advertising IDs, **features you don’t want or disagree with, or updates that may change the way you interact with your PC.**
> 
> ### _I really don’t need [ESM notifications]._

Now I added the bold and changed "Cortana" to "ESM notifications", but I trust you get the point.  This did change how I interacted with my desktop server and  I don't want those update notifications.   I'm not sure why I am so viscerally opposed to these notifications (by this point the principle of the thing likely overrides anything else), but it likely has to do with the fact that I've trained myself to pay attention to that line when I log into my machine to see if I need to run updates.  Now there's something else in that space that hits loss-aversion bias (partially why it's there in the first place) for something I don't need, didn't ask for, don't want, can't disable easily, and its explanation feels Orwellian (if I don't need the ESM updates because I'm getting all the updates I need during LTS coverage then what is ESM updating?*).  

_Put simply:  If you add something to an area of important notifications, it better be something important or you've demanded my attention in an area I've trained myself to expect important notifications for something that isn't.  Is it crying wolf?  Sure, to some extent._

**Second, in my opinion, the UA tools should have a command that addresses these messages by updating the apt hook, disabling and masking the systemctl services/triggers/timers, patching apt-check, etc.**  Further, I seriously question the decision to put all of this into apt_check.py: Instead of including the EMS checks in apt_check.py, create another update.motd.d script, e.g., `91-esm-updates-available` that runs e.g., `/usr/lib/update-notifier/esm-check -> esm_check.py` that writes to `/var/lib/update-notifier/esm-updates-available` that is displayed by `91-esm-updates-available`.  **Cynically, I feel there is no reason to have these two systems intertwined the way they are except to frustrate attempts to pull them apart.**   If the relevant place to bring this up is with update-notifier-common  then that is another avenue I may explore.

Third, I'm extremely disappointed in the referenced FAQ.  It is **a lot** of words to tell me hey, there's this file in `/apt/apt.conf.d/`; figure it out yourself.  It does not go into sufficient detail for an average user to know that, e.g., **you comment out lines in the apt.conf.d scripts with // instead of #!**  I would not have known that had it not been for @orndorffgrant mentioning it in the above post.  

*ESM appears to do a poor job of explaining what the additional updates are when the notification appears.  If, perhaps, there was a command that showed what it was updating over standard APT updates, then perhaps it would seem a little less opaque (and therefore frustrating).  Further, the reasons for ESM for a non-production personal user are not made clear.  What is the core benefit to me to go through the process of setting this up if I'm still going to get all the needed security updates?

Case in point:

> 15 additional security updates can be applied with ESM Apps.
>  Learn more about enabling ESM Apps service at https://ubuntu.com/esm

What are these updates and how do I decide if they're relevant or needed?  Going to ubunut.com/esm isn't going to tell me that the way apt will show which updates are available.  Why not?

**Comment by orndorffgrant** [comment]
Hi @iconoclasthero,

First, I appreciate your feedback. This helps us understand where we need to improve, especially in our communicating: both in our documentation and in these messages on Ubuntu systems.

I'll try to respond to all of your points but let me know if I miss anything

---

> I'm getting all the updates I need during LTS coverage then what is ESM updating?

> What is the core benefit to me to go through the process of setting this up if I'm still going to get all the needed security updates?

> If you add something to an area of important notifications, it better be something important

"ESM **Apps**" is distinct from "ESM **Infra**" and "ESM Infra" was previously known as just "ESM", so I understand the confusion. We are already reconsidering these naming decisions.

ESM **Apps** includes additional security updates _during normal LTS coverage_ for software from the universe repo. So if you see a notification that looks like this:
```
15 additional security updates can be applied with ESM Apps.  
Learn more about enabling ESM Apps service at https://ubuntu.com/esm
```
That means that there are currently CVEs that affect packages that you have installed from universe. And it means that those CVEs are fixed in updates available from ESM Apps for free.

The key part is _there are currently CVEs that affect packages that you have installed_. So we consider this to be important - that is why we put it in a place where it will be noticed. 

We appreciate any suggestions you have on making that message clearer, without also making it too verbose  - it's hard to balance that :upside_down_face:

---

> If, perhaps, there was a command that showed what it was updating over standard APT updates, then perhaps it would seem a little less opaque

> Going to ubuntu.com/esm isn't going to tell me that the way apt will show which updates are available

If you leave `/etc/apt/apt.conf.d/20apt-esm-hook.conf` intact, then there should be output in `apt upgrade` that tells you exactly what packages have security fixes available in ESM Apps.

You can also run `pro security-status --esm-apps` for a wall of text of information about how ESM Apps might apply to your system. We're actively iterating on this command, so the output will likely change in the future and any feedback you have on it is appreciated!

An important thing that we're lacking right now is a way to easily answer the question: "What specific CVEs do the ESM Apps updates address?" so that you can determine if you actually care about a particular security update. We're working on this.

---

> I seriously question the decision to put all of this into apt_check.py
> ...
> Cynically, I feel there is no reason to have these two systems intertwined the way they are except to frustrate attempts to pull them apart

That is cynical - and wrong :) The real reason: that script is where normal update notifications were inserted into MOTD before ESM, and ESM notifications are also update notifications of a sort, so topically they are closely related. The ESM messages also rely on querying the same APT information as the normal update messages, and most of that was already implemented in apt_check.py. So it was technically convenient and easier to do it in the same script.

That being said, I think your idea of separating the ESM notifications to have their own script and separate update-motd.d config file is a great idea! For all the reasons you've stated. I highly recommend you open a bug against update-notifier [here](https://bugs.launchpad.net/ubuntu/+source/update-notifier) with your suggestion (if it works out, it might end up being someone from the Ubuntu Pro team who implements it, but that is the proper place to have the discussion so that other stakeholders interested in update-notifier can be aware and contribute).

---

> the UA tools should have a command that [disables] these messages

As I described above, we consider these notifications to be important security-related messages. I agree that if you're a technical user who understands the risk, then you should be able to customize your system to remove them if you'd like (and again your suggestion about the update-notifier script would help here). I'm not convinced, though, that it warrants a special command to do it, so long as the system customizations aren't overly burdensome. I recognize from this conversation that currently it _is_ overly burdensome, but I'd rather fix the problems that make it burdensome, rather than paper over them with a new "disable all ESM messages" command.

---

> you comment out lines in the apt.conf.d scripts with // instead of #

I think either `//` or `#` will work to create comments in those files.

---

> I'm extremely disappointed in the referenced FAQ

The FAQ is trying to serve the needs of a large number of people with different needs. It's main purpose is to explain "What is Ubuntu Pro and ESM Apps" from a few different angles. We may add the characters that can be used to comment the apt config - to help with your specific critique.

---

Sorry for the wall of text, but I hope this helps explain the state of things. We do appreciate feedback and especially any suggestions on how to make these messages more helpful, explanatory and, if possible, less annoying :)

**Comment by orndorffgrant** [comment]
We're adding documentation about the MOTD messages in #2534 and I went ahead and submitted a bug to update-notifier with the request to untangle the normal and ESM update MOTD messages here:

https://bugs.launchpad.net/ubuntu/+source/update-notifier/+bug/2015420

Further discussion about how to disable the ESM MOTD messages from update-notifier should continue in that bug since that is the package where the changes would need to be made.  So I'm closing this one.
