### ISSUE TITLE
Even with conflicts of CVE coverage in distro vs ESM, the "Get more security updates" message is shown as is

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu-pro-client#2462]
```
$ pro version
27.13.5~22.04.1
```

On jammy, a security update has been released for `imagemagick` today as a distro update (not ESM):
```
imagemagick (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1) jammy-security
```
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/2004580

According to the changelog, it fixes the following two CVEs:
- [CVE-2022-44267](https://ubuntu.com/security/CVE-2022-44267)
- [CVE-2022-44268](https://ubuntu.com/security/CVE-2022-44268)

Although the current ESM package (`8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1+esm1`) covers more than 10 CVEs, it hasn't covered two exact CVEs above yet if I'm not mistaken.

This kind of conflict could happen at any point in any package so the following message should be tweaked especially when this kind of non-fast-forward-able situation happens.

> Get **more security updates** through Ubuntu Pro with 'esm-apps' enabled:
>   imagemagick

```bash
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  imagemagick libopenexr25 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6
  imagemagick-6.q16 libmagickcore-6.q16-6 imagemagick-6-common
Learn more about Ubuntu Pro at https://ubuntu.com/pro
The following packages have been kept back:
  isc-dhcp-client isc-dhcp-common python3-software-properties software-properties-common
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

```bash
$ apt policy imagemagick
imagemagick:
  Installed: 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1+esm1
  Candidate: 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1+esm1
  Version table:
 *** 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1+esm1 500
        500 https://esm.ubuntu.com/apps/ubuntu jammy-apps-security/main amd64 Packages
        100 /var/lib/dpkg/status
     8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1 500
        500 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
     8:6.9.11.60+dfsg-1.3build2 500
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

**Comment by orndorffgrant** [comment]
Thanks for reporting this situation @nobuto-m!

There are processes in place so that ESM patches get re-applied on top of any non-pro updates, so this won't happen in the general case.

The imagemagick case described here was due to a weird situation that tripped up the process (a couple additional updates went into jammy-security in quick succession after the initial one). This was resolved by the security team. This kind of situation is monitored closely to assure that that if it does occur, it is resolved quickly.

So in total, "Get more security updates" is still the correct message here and I'll close this bug. Let me know if you have any additional questions.
