### ISSUE TITLE
docs: support diagramming without image files

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2559]
We could use https://github.com/mgaitan/sphinxcontrib-mermaid or something similar to more easily add and edit diagrams in our documentation.

Not urgent but WDYT @s-makin?

**Comment by s-makin** [comment]
If it makes creating and maintaining diagrams easier then it could definitely be worth adding yeah. I just want to do a bit of investigating on how it is for accessibility, but I'll report back here with my findings next week.

**Comment by s-makin** [comment]
So, after doing some digging, it looks like [they've already been working](https://github.com/mermaid-js/mermaid/issues/2732) hard on the accessibility problem. Accessibility is always going to be tricky with content of this type, because it's hard to write good alt text or captions that really describes what the content is conveying (in a brief way). However, that problem exists for any diagram/flow chart. 

Although they're not fully there yet, the fact that they are aware of the issues and are actively working on various ways of improving their accessibility means that this is automatically better than the standard ways of creating these images. This proposal gets a thumbs up from me - thanks for bringing it to my attention!

**Comment by s-makin** [comment]
It occurs to me that this needs an action - over the next cycle I'll add some documentation around this to our devdocs and link the PR here when it's up
