### ISSUE TITLE
Bug: integration tests missing for mantic, noble

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu-pro-client#2871]
**Description of the bug**

The integration tests should also run on mantic and noble. Now they only run up to lunar:

https://github.com/canonical/ubuntu-pro-client/blob/main/.github/workflows/ci-integration.yaml#L68

**Expected behavior**

The integration tests should run on all curently supported Ubuntu releases, and the devel release (which is going to be the next LTS).

**Current behavior**

The integration tests do not run on mantic nor noble.

**To Reproduce**

Run integration tests on github.

**System information:**

- Pro Client version: main

**Additional context**

**Comment by orndorffgrant** [comment]
@renanrodrigo and @lucasmoura reminded me that we purposefully don't run integration tests on the dev release on every PR. That is because the dev release changes frequently and frequently causes errors unrelated to pro-client. IOW, the signal-to-noise ratio is too low. Because of that, we won't add noble to the integration test runs on every PR until after Feature freeze, when noble is stable enough to be a reliable testing base.

We will go ahead and add the package build CI for noble though
